### ISSUE TITLE
Une fonction supprimant un commentaire

### ISSUE THREAD

**Issue by Kylian2** [Kylian2/vote-right#13]
Il faut une fonction qui supprime un commentaire, (le commentaire est conservé dans la base mais la valeur de suppressor est remplie). 

`delete_comment(comment_id, user_id)`

**Comment by mguiborat** [comment]
Je l'ai déjà faite, elle a été merge. La fonction se nomme "delete_comment_and_resolve_reports"

**Comment by Kylian2** [comment]
Je parlais d'une fonction qui permettrai de supprimer un commentaire sans passer par un report
