### ISSUE TITLE
Modifier les couleurs des communautés : mettre le code HEX et pas le nom de la couleur

### ISSUE THREAD

**Issue by Kylian2** [Kylian2/vote-right#8]
*ex*: 
(1, 'Association des arts et traditions populaires', '100004.png', '1F389', **'Rouge'**, NULL, 86000.00, 40420.00, 74);
devient (1, 'Association des arts et traditions populaires', '100004.png', '1F389', **'#DE3D59'**, NULL, 86000.00, 40420.00, 74);

*La liste des couleurs disponibles*: 

$color-1: #5AB7EE;
$color-2: #FDBE55;
$color-3: #FB961F;
$color-4: #13329F;
$color-5: #8700CF;
$color-6: #F669D9;
$color-7: #DE3D59;

**Comment by Laren21** [comment]
Normalement c'est bon, la correction sera effective dans la branche main quand on aura merge la branche sur laquelle je fais mes insertions actuellement.
